title: Preston Dresser
theme: minima
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - file.md

author: Preston Dresser
email: preston.dresser16@gmail.com
github_username:  03predo
linkedin_username: preston-dresser
